name: Run Prettier

on:
  pull_request:
    branches: [main]
    paths: [src/**]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: install and run formatter
        run: |
          npm ci
          npm run format

      - name: commit change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: the code has been formatted!"
          branch: ${{ github.head_ref }}
