name: Publish Post

on:
  schedule:
    - cron: "0 23 * * 1,3,5"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a branch and run the script
        run: |
          git switch -c publish-post
          ./scripts/publish-post.sh

      - name: Check for changes
        id: check-changes
        run: |
          git diff --exit-code || echo "::set-output name=changes::true"

  commit-push:
    needs: [publish]
    runs-on: ubuntu-latest
    if: ${{ needs.publish.outputs['check-changes'] == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: config git - commit - push
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin main --no-ff
          git add .
          git commit -m "chore: publish post 🎉"
          git push origin publish-post
      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base=main --head=publish-post -f
