name: Publish Post

on:
  schedule:
    - cron: "0 23 * * 1,3,5"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a branch and run the script
        run: |
          git switch -c publish-post
          ./scripts/publish-post.sh

      - name: Check for changes
        id: check-changes
        run: |
          check_changes=$(<<< "$(git status --porcelain)")

      - name: Commit changes or exit the process
        run: |
          if [ -n "$check_changes" ]; then
            echo "Changes detected. Proceeding with commit and push..."
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git config --local user.name "${{ github.actor }}"
            git pull origin main --no-ff
            git add src/content/ src/drafts 
            git commit -m "chore: the post is published! 🎉"
            git push -u origin HEAD
          else
            echo "No changes detected. Exiting the process."
            exit 0
          fi

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base=main --head=publish-post -f
