name: Publish Post

on:
  schedule:
    - cron: "0 23 * * 1,3,5"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create a branch and run the script
        run: |
          git switch -c publish-post
          ./scripts/publish-post.sh

      - name: Check for changes
        run: |
          changes=$(git status --porcelain)
          if [ -z "$changes" ]; then
            echo "No changes to commit. Exiting..."
            exit 0
          fi

      - name: Commit and push
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin main --no-ff
          git add .
          git commit -m "chore: publish post 🎉"
          git push origin publish-post

      - name: Create pull request
        run: |
          gh pr create --base=main --head=publish-post --fill
        env:
          GH_TOKEN: ${{ github.token }}
