name: Publish Post

on:
  schedule:
    - cron: "0 2 * * 1,3,5"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run publishPost script
        run: |
          git switch -c publish-post
          node scripts/publishPost.js

      - name: Check for changes
        id: changes
        run: |
          if git diff --cached --exit-code; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes or exit the process
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          echo "Changes detected. Proceeding with commit and push..."
          git add src/content/ src/drafts
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git pull origin main --no-ff
          git commit -m "chore: the post is published! 🎉"
          git push -u origin HEAD

      - name: Create PR
        if: steps.changes.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --base=main --head=publish-post -f
